version: "3.8"

services:
  ainpal-api:
    build: .
    container_name: ainpal-api
    ports:
      - "4231:8000"
    environment:
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - .:/app
    restart: always
